image: atlassian/default-image:latest

pipelines:
  branches:
    develop:
      - step:
          caches:
            - node
          deployment: staging
          script:
            - cat ./deploy.sh | ssh -tt staging@outright.xyz
            - echo "Deploy step finished"
