<<<<<<< HEAD
image: atlassian/default-image:latest

pipelines:
  branches:
    development:
      - step:
          caches:
            - node
          deployment: staging
          script:
            - cat ./deploy.sh | ssh -p 19022 -tt zmist@zmist.tech
            - echo "Deploy step finished"
=======
# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
>>>>>>> 6501b9d7e4d1d16bc9eb8ce51401c8fcd1f2623f
