image: atlassian/default-Image:latest

pipelines:
  branches:
    development:
      - step:
          caches:
            - node
          deployment: staging
          script:
            - cat ./deploy.sh | ssh -p 19022 -tt zmist@zmist.tech
            - echo "Deploy step finished"
